### PR TITLE
V19

### PR DESCRIPTION
**Pull request by azhawkes**
I fixed a user-reported bug that prevented recording events in frames/iframes when running with the v2 manifest (Firefox). I also noticed that text selectors recorded in frames weren't getting the frame selector prepended, so I fixed that too.

Also upgraded the web extension polyfill library to v0.9.0.

### CODE REVIEW

**Comment by azhawkes** [comment]
I went ahead and published the new Firefox version only for now.

**Review by konfrontend — APPROVED** [review]
@azhawkes Looks good. I think we can attach one more small task to v19. [L-232](https://linear.app/loadster/issue/L-232/browser-extension-on-off-switch-behaves-weirdly)

**Comment by azhawkes** [comment]
@konfrontend I figured out what the main issue was. 

A user has an app that uses a frameset, and clicking in one frame causes navigations to happen in another frame. We were only registering the content scripts in all frames when the tab navigates, so after a navigation within a sub-frame the content scripts weren't present, and recording failed. With this change we'll watch for navigations in those sub-frames and register the content scripts even if the top-level page has not changed.

Look ok?

**Comment by azhawkes** [comment]
@konfrontend Thanks for including L-232 btw.

**Review by konfrontend — APPROVED** [review]
Looks good. As far as I can tell, it works. I found and fixed a little issue with the tab not flashing if the page has nested frames.

**Review by konfrontend — APPROVED** [review]

**Pull request merged**
