### PR TITLE
Use editorconfig and eslint

### PR DESCRIPTION
**Pull request by konfrontend**
@azhawkes 
To make it more consistent with the dashboard, I also had to add `.eslintrc` in addition to `.editorconfig`.
This does not work automatically, but can be used with a globally installed Eslint and the command `eslint js --fix`

Oh, do we need to increment version here?

### CODE REVIEW

**Comment by konfrontend** [comment]
[Reformat loadster-browser-extension and add .editorconfig](https://trello.com/c/XS8qtZDD/456-reformat-loadster-browser-extension-and-add-editorconfig)

**Comment by azhawkes** [comment]
Yep, I incremented the version, planning to do a release. Even though no functionality is changing, I think the Chrome and Firefox review process might see the big diff and flag it for review, so it would be nice to get this version out there so we can get through the review and don't get delayed next time when we have something more critical.

Looks like eslint is producing some warnings... would you like to fix any of them in this PR or ship it like this?

**Comment by konfrontend** [comment]
> Yep, I incremented the version, planning to do a release. Even though no functionality is changing, I think the Chrome and Firefox review process might see the big diff and flag it for review, so it would be nice to get this version out there so we can get through the review and don't get delayed next time when we have something more critical.
> 
> Looks like eslint is producing some warnings... would you like to fix any of them in this PR or ship it like this?

Got it!
Yes, I thought to ship it like this. I had to disable some of the rules to pass the tests, but some of them look worthy of attention, so I added warnings instead.
Some of these warnings  can not be fixed right now (without using Webpack)

**Review by azhawkes — APPROVED** [review]
:+1:

**Pull request merged**
