### PR TITLE
Manifest v3 migration

### PR DESCRIPTION
**Pull request by konfrontend**
@azhawkes Definitely got carried away with this, but now we're ready for the MV3 updates!

I separated the logic of the two modes (browser and protocol recording). So now it's more efficient and manageable. In addition it seems like a good basis for mixing the two modes together if we ever want that. 
Most notably the recording always happened in both modes, no matter what type of recording the user intended. Now we are less greedy for user resources. Also now more robust error handling.

Since Firefox doesn't support v3 yet, I made the whole thing run under the v2 flag, although it's basically v3 with a few minor changes, mostly related to manifest.json. So when it comes to switching it will be a matter of changing the version number.

This is a draft, because I wanted to add https://linear.app/loadster/issue/L-210/improve-automatic-selectors-when-recording here to speed up the google review.

### CODE REVIEW

**Comment by azhawkes** [comment]
@konfrontend Looks good, I like the cleanup! So we're okay on the HTTP side with `webRequest` instead of `webRequestBlocking`? Are we still able to get POST bodies and the `Referer` header?

**Comment by konfrontend** [comment]
@azhawkes Haven't seen any issues yet. You mean requestBody, right? I was able to record the Loadster login process (from netlify) and run the script of that recording successfully. No blocking. Works for both manifests v2 and v3. 
I don't see us putting a lot of headers in the recorded steps even though they are available(and coming) at recording including Referer.

Oh and here is the manifest v3. Not sure if we should include this in the package before the full switchover to v3.

```
{
  "manifest_version": 3,
  "name": "Loadster Recorder",
  "description": "Create test scripts to run in Loadster and Speedway.",
  "version": "15",
  "icons": {
    "16": "images/icon-16x16.png",
    "32": "images/icon-32x32.png",
    "48": "images/icon-48x48.png",
    "128": "images/icon-128x128.png",
    "256": "images/icon-256x256.png"
  },
  "action": {
    "default_icon": "images/icon-32x32.png",
    "default_popup": "popup.html"
  },
  "background": {
    "service_worker": "js/service-worker.js",
    "type": "module"
  },
  "minimum_chrome_version": "92",
  "content_scripts": [
    {
      "matches": ["*://localhost/*", "https://loadster.app/*", "https://speedway.app/*"],
      "js": [
        "js/browser-polyfill.min.js",
        "js/content.js"
      ],
      "run_at": "document_start"
    }
  ],
  "permissions": [
    "storage",
    "scripting",
    "webRequest",
    "webNavigation"
  ],
  "host_permissions": [
    "*://*/*"
  ]
}

```

**Comment by azhawkes** [comment]
@konfrontend This looks good. About the manifest, I'd say let's commit v3 as `manifest-v3.json` so it exists in the project, and we can maintain both versions for a little while. I can rename it manually when packaging for Chrome.

**Comment by konfrontend** [comment]
@azhawkes it's ready to go now, but it won't let me to merge without your approval

**Comment by azhawkes** [comment]
Looks good, thanks!

**Review by azhawkes — APPROVED** [review]

**Pull request merged**
