### PR TITLE
L-914 Record Click events when significant

### PR DESCRIPTION
**Pull request by konfrontend**
@azhawkes With this update, we will be able to use `vite` bundler, which simplifies cross-browser development and helps keep the code organized. It comes with `eslint`, hot module replacement, and most importantly, the ability to directly use any existing `npm` package. The [webext-bridge](https://serversideup.net/open-source/webext-bridge/docs) lib proved particularly useful here. Communication between modules in this extension was never easy. Now it became at least manageable.

To be honest, I can't say this update was as urgent or important as I had hoped. At some point it turned into a real nightmare... I finally managed to put it all together and I think it was worth it. This update comes with the eventListener detector, and we can continue to add new features on top of that. I just want to test and clean it up a bit more before it's ready to deploy.

### CODE REVIEW

**Comment by konfrontend** [comment]
Building for Chrome or Firefox overwrites the `dist` folder, which contains all the files needed for production. We can build into separate folders too. Let me know if we need that. 

The app version is now linked to the `package.json` version. So we just increment that instead of the manifests. They are now fully dynamic and do not require manual updating.

**Comment by azhawkes** [comment]
@konfrontend No worries, sometimes that's the way it goes...

It would be nice to build them into subfolders of the dist (dist/chrome and dist/firefox) just to make packaging them a little less error-prone.

Do the 'dev' and 'dev:firefox' scripts actually run the extension in the browser? It seemed to pop open a browser but not running the extension.

Doesn't look like it added any new browser permission requirements, right?

**Comment by konfrontend** [comment]
@azhawkes Dev commands actually launch the extension, but not the recording. That requires an action from the Loadster dashboard. But we can push some of the functionality back to the extension level so it works more like a classic browser extension.
Dev commands also open the target browser, you can use `.webextrc.sampe` (remove .sample) to open a specific page or launch a specific browser profile.

**Comment by konfrontend** [comment]
Oh, and thank you for your understanding. And no, no additional permissions are required.

**Comment by konfrontend** [comment]
@azhawkes Hooray, at last! This is ready for review. 
This comes with smart selectors for click events. When looking for a selector for a click event, we now look for the closest ancestor with a matching event listener and create a selector for that element instead of the original `e.target`.
I also included the npm version of the finder lib instead of the unpacked version. The same goes for the browser polyfill. We don't need to keep it in the source code anymore.

**Comment by azhawkes** [comment]
@konfrontend Glad it finally came together! The build process does look like it will be easier to maintain in the long run.

I tested a bit with the click selectors, and couldn't get it to work. Specifically I made [this little page here](https://loadster-sandbox.netlify.app/nested-button.html) and then I clicked 3 times, once on each nested child and then once on the outer `#clickme` button itself. It still recorded them as three different selectors:

image

I was thinking it would have done `#clickme` all three times since that's the one with the event handler.

I also tested [this other page](https://loadster-sandbox.netlify.app/hover-menu.html) that I copied from somewhere, using a JavaScript hover menu. It didn't seem to record the Hover event. Looking over the commits, maybe the Hover stuff didn't make it into this PR yet?

**Comment by konfrontend** [comment]
@azhawkes Oh, thanks! It looks like the content script isn't always getting to the page before it loads. This little page, while a bit unrealistic, shows that well. Okay, I'll take a closer look at that.

**Comment by konfrontend** [comment]
@azhawkes Now it works! I also paid extra attention to Firefox. There were too many changes, but I think the extension got a decent update after all.

As for hover events, it is now possible to work in this direction. Although conceptually it is a bit more complicated. There are basically two main problems. The first is that, unlike clicks, layout changes can come from CSS (:hover). I'm pretty sure there's no way to control this from javascript. The second is that a hover event can precede a layout change, but have nothing to do with it.

I had some doubts about hover events from the start, but now that I've refreshed my memory on how extensions work... Now we can definitely add some spice to the recording, maybe just not through hover events. What do you think?

**Comment by azhawkes** [comment]
@konfrontend Sorry, didn't get to this today but I should be able to test it again tomorrow. 

I agree that CSS hover properties are going to be tricky to deal with. We can set those aside for now.

However, the more I think about it, the more I think if the user hovers on an element with a JavaScript hover event handler attached (`mouseenter` or `mouseover`), then it should be reasonably safe to just record a Hover event. Having extra Hover events in the script actually isn't likely to be harmful or have any ill effect besides a bit of clutter. I know it will never be 100% accurate, but if we can record even half of these it would be quite helpful to new users.

**Comment by konfrontend** [comment]
@azhawkes You're right, we've come this far, there's no reason not to push it a little more:) `mouseover` and `mouseenter` are now supported. To make this work, this [tiny update](https://github.com/loadster/loadster-dashboard/pull/896) is required. It's harmless, so I've already merged it.

**Review by azhawkes — APPROVED** [review]
Looks good and it seems to be working nicely. I'll merge and deploy to the stores.

**Pull request merged**
